# Generated by Django 2.1.2 on 2018-10-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='helper',
        ),
        migrations.AddField(
            model_name='event',
            name='helpers',
            field=models.ManyToManyField(blank=True, null=True, to='frontend.Helper'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slot',
            field=models.CharField(choices=[('MORNING', 'am'), ('EVENING', 'pm')], max_length=12),
        ),
    ]
