# Generated by Django 2.1.2 on 2018-10-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20181026_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='helpers',
            field=models.ManyToManyField(blank=True, to='frontend.Helper'),
        ),
    ]
